project_id = "ckgmdsdoywkncduigdkk"

[functions.chat-rota399]
verify_jwt = false

[functions.plano-governo-ai]
verify_jwt = false

[functions.geolocate-visitor]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
